syntax on
augroup numbertoggle
    "Number mode changes between insert and normal mode
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
    autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END

call plug#begin('~/vimfiles/plugged')

Plug 'gruvbox-community/gruvbox'
Plug 'leafgarland/typescript-vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mbbill/undotree'
Plug 'maxboisvert/vim-simple-complete'
Plug 'jsborjesson/vim-uppercase-sql'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'itchyny/lightline.vim'
Plug 'shinchu/lightline-gruvbox.vim'
Plug 'mattn/emmet-vim'

call plug#end()

colorscheme gruvbox
let g:gruvbox_contrast_light='soft'
let g:gruvbox_contrast_dark='soft'
let g:gruvbox_number_column='bg0'

let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

let g:netrw_banner=0
let g:netrw_browse_split=2
let g:netrw_winsize = 25

let g:ctrlp_match_window = 'bottom,order:btt,min:1,max:15,results:50'
let g:ctrlp_open_new_file = 't'
let g:ctrlp_working_path_mode = 'rw'

let mapleader = " "

let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
let g:user_emmet_leader_key='<C-k>'
"let g:user_emmet_expandabbr_key = '<Tab>'

"TEMP
"let g:netrw_liststyle = 3
let g:netrw_altv = 1

"let g:lightline = {
"  \     'active': {
"  \         'left': [['mode', 'paste' ], ['readonly', 'filename', 'modified']],
"  \         'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding']]
"  \     }
"  \ }

"let g:lightline = {'colorscheme': 'custom1'}
let g:lightline = {}
let g:lightline = {'colorscheme': 'gruvbox'}
set laststatus=2
set noshowmode

"Quick access directories
nnoremap <Leader>.home :cd C:\Users\ryany\<CR>
nnoremap <Leader>.ryayoung :cd C:\Users\ryany\ryayoung<CR>
nnoremap <Leader>.proj :cd C:\Users\ryany\ryayoung\INFO3300<CR>
nnoremap <Leader>.web :cd C:\Users\ryany\web-programming<CR>
nnoremap <Leader>.plugged :cd C:\Users\ryany\vimfiles\plugged<CR>
nnoremap <Leader>.du :cd C:\Users\ryany\Onedrive\ -\ University\ of\ Denver\School\Y4Q1<CR>
nnoremap <Leader>.btr :cd C:\Users\ryany\Onedrive\ -\ University\ of\ Denver\Back\ To\ Roots<CR>
nnoremap <Leader>.www :cd C:\Users\ryany\Onedrive\ -\ University\ of\ Denver\School\Y4Q1\COMP\ 3410\ WWW\ Programming<CR>
nnoremap <Leader>.dw :cd C:\Users\ryany\Onedrive\ -\ University\ of\ Denver\School\Y4Q1\INFO\ 3300\ DW<CR>
nnoremap <Leader>.pm :cd C:\Users\ryany\Onedrive\ -\ University\ of\ Denver\School\Y4Q1\INFO\ 3340\ Project\ Management<CR>
nnoremap <Leader>.mgmt :cd C:\Users\ryany\Onedrive\ -\ University\ of\ Denver\School\Y4Q1\MGMT\ 3000\ Policy\ Strategy<CR>



